### ISSUE TITLE
paper about this project

### ISSUE THREAD

**Issue by wangbq18** [aistairc/DeepEventMine#1]
hello, Do you have any papers on this project？

**Comment by trieuhl** [comment]
Hi, thanks for your interest. Yes, we have a paper. We expect to publish it soon, and will let you know when the paper is published.

**Comment by trieuhl** [comment]
Hi, you can check our paper here. It is noted that this is not the final version in terms of the journal format.
https://doi.org/10.1093/bioinformatics/btaa540

**Comment by wangbq18** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好!我已收到您的邮件！
