### ISSUE TITLE
version numbers of requirements

### ISSUE THREAD

**Issue by leonweber** [aistairc/DeepEventMine#5]
Hey, 

thanks for your awesome work! I'm having troubles when using your models for prediction, possibly because version mismatches of the requirements. For instance, I'm getting: 

```bash
$ sh run.sh pc predict gold dev
UserWarning: Trying to unpickle estimator MultiLabelBinarizer from version 0.21.3 when using version 0.23.1. This might lead to breaking code or invalid results. Use at your own risk.
...
ValueError: zero-size array to reduction operation maximum which has no identity
```

Could you please specify the exact versions of the required packages that would allow me to reproduce the results?

**Comment by trieuhl** [comment]
Hi, thank you for your question and comment. I forgot to add the version and requirements. I have updated. Could you try again and let me know?

**Comment by leonweber** [comment]
Hi, thanks for your quick reply! I had additional to do `pip install cchardet` which resolved the error above.
`pip install scikit-learn==0.21.3` resolved the warning.

**Comment by trieuhl** [comment]
Thanks.
